### PR TITLE
Make stdout the default output destination for all types

### PR DESCRIPTION
**Pull request by ThinkOpenly**
By default, output will go to stdout.
Also, remove automatic file name generation.
Output destination is either explicitly specified, or will be stdout.

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>

### CODE REVIEW

**Comment by rpsene** [comment]
Should it work when I only select the name of the file output?  For example: sca --output-name=sene ./sample

In this case I still got the results printed in my screen and got no file saved.

When I try sca --output-type=json --output-name=sene ./sample, the result is:

Traceback (most recent call last):
  File "/usr/local/bin/sca", line 24, in <module>
    sca.main()
  File "/usr/local/lib/python2.7/dist-packages/sca/sca.py", line 167, in main
    controller.run_sca(binary_path, binary_args, sca_options)
  File "/usr/local/lib/python2.7/dist-packages/sca/controller.py", line 76, in run_sca
    core.output_sca(group_problems, outfile, output_type)
  File "/usr/local/lib/python2.7/dist-packages/sca/core.py", line 174, in output_sca
    output_sca_json(problems_dict, outfile)
  File "/usr/local/lib/python2.7/dist-packages/sca/core.py", line 161, in output_sca_json
    outfile.write(problems_dict.get(key).to_json())
AttributeError: 'str' object has no attribute 'write'

**Comment by ThinkOpenly** [comment]
will fix and submit a new pull request

**Comment by rpsene** [comment]
With the this patch it is no longer saving  neither in txt nor in json. And the output get printed with some \ chars:
solution": "\n\tSpecify the GNU extension \"__attribute__ ((optimize (\"unroll-loops\")))\"    \n\ton the function containing the loop.    \n\tExample:    \n\t\tvoid __attribute__((optimize(\"unroll-loops\"))) foo(void);    \n\n\tNote: Unrolling loops can sometimes negatively impact performance,    \n\tso validation of its impact is recommended."

**Comment by ThinkOpenly** [comment]
Closing. Preparing to archive this project.

**Pull request closed without merging**
